### ISSUE TITLE
Repeating math equations while using Mathlified

### ISSUE THREAD

**Issue by sandeshkatakam** [kelvinsjk/mathlified#5]
I started using mathlified for my blog and when I use {@html inlineMath} or {@html displayMath}. The equations rendered on the blog are repeated twice.  The one rendered with the package and other with normal typefont. Is there any fix for this? 

Thank you in advance
<img width="185" alt="Screenshot 2023-05-22 154952" src="https://github.com/kelvinsjk/mathlified/assets/88609382/8e9c21a3-b9e2-46c4-b36c-08a683947c2d">

**Comment by kelvinsjk** [comment]
It sounds like a css issue. Have you included the katex stylesheet? (eg `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.7/dist/katex.min.css" integrity="sha384-3UiQGuEI4TTMaFmGIZumfRPtfKQ3trwQE2JgosJxCnGmQpL/lJdjpcHkaaFwHlcI" crossorigin="anonymous">` 
in the `<head>` section of the html)

**Comment by sandeshkatakam** [comment]
Yes, I have linked the stylesheet in the head section of src/app.html. I am still getting repeated equations.

**Comment by kelvinsjk** [comment]
Do you have your code online so I can take a look at it? Or perhaps a reproduction

**Comment by sandeshkatakam** [comment]
Yeah the source code of my blog is hosted on github

GitHub Repo: [https://github.com/sandeshkatakam/Machine-Learning-Blog](url)

It would be of great help If I get this issue fixed. most of my blog posts rely on math equations

**Comment by kelvinsjk** [comment]
I don't see the use of mathlifier in the repo. Have you pushed your code yet? (maybe to a separate branch if you don't want it live)

**Comment by sandeshkatakam** [comment]
ohh sorry.. I haven't pushed my code yet.. I did it just now.
sorry for the inconvenience caused.
