### ISSUE TITLE
math is not exported in version 2.0.1

### ISSUE THREAD

**Issue by charlyoleg2** [kelvinsjk/mathlified#8]
mathlifier.js doesn't export 'math' any more.

v2.0.1 exports:
export {
  Io as mathlifier,
  ps as mathlifierDj,
  os as mathlifierFactory,
  hs as mathlifierTex,
  Eo as resetOptions,
  Oo as setOptions
};

whereas v1.3.5 exports:
export {
  align,
  alignStar,
  alignat,
  alignatStar,
  bold,
  display,
  em,
  emph,
  eqn,
  eqnStar,
  equation,
  equationStar,
  gather,
  gatherStar,
  html,
  htmlTex,
  linebreak,
  math,
  newParagraph,
  newline,
  strong,
  tex
};

**Comment by kelvinsjk** [comment]
Ah, yes. That was a big oversight on my part. Thanks for catching it.

Have just published v2.0.2 which should add back

- math
- display
- align
- gather
- equation, eqn
- alignat

(and their starred variants)

**Comment by charlyoleg2** [comment]
Thank you for the quick fix. It works on my side.

**Comment by charlyoleg2** [comment]
'math' and others are exported as in the v1.x version. The issue is fixed.
