### ISSUE TITLE
TypeError while using v2.0.1 on server-side

### ISSUE THREAD

**Issue by charlyoleg2** [kelvinsjk/mathlified#9]
With node v20.17.0 and mathlifier v2.0.1 I get the error:
```
TypeError: n.forEach is not a function
    at file:///parametrix/node_modules/mathlifier/dist/mathlifier.js:7:11
```

**Comment by kelvinsjk** [comment]
Can you check if v2.0.2 solves this?

**Comment by charlyoleg2** [comment]
v2.0.2 solves the issue.
Actually I was using 'mathlifier' as a replacement for 'math', which might not be a good idea.

**Comment by kelvinsjk** [comment]
For "light sprinkles" of mathematics markup I think the 'math' function works well enough.

In v2 I've replaced the KaTeX dependency (which requires the KaTeX css file to function. You can remove the link to that file if upgrading to V2). It outputs MathML (supported by most modern browsers now) generated by Temml instead, so now without any additional files _most_ mathematical markup should still render well enough. Temml's own css file (I may get around to getting that up on a cdn for easy usage) then fixes rendering of some edge cases).

The extra features in v2 are mainly geared towards writing prose mixed with mathematical markup.

PS: <https://charlyoleg2.github.io/parametrix/> is mightily impressive!

**Comment by charlyoleg2** [comment]
Parametrix uses now Mathlifier v2 with `Temml-Local.css` and it looks good.
I have also tried with `Temml-Latin-Modern.css` but the file `latinmodernmath.woff2` is missing and I could not find it somewhere in the web.

**Comment by kelvinsjk** [comment]
<https://github.com/fred-wang/MathFonts?tab=readme-ov-file#using-math-fonts-on-your-web-site> provides a zip download for the different fonts
